/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        'geist': ['Geist_400Regular', 'system-ui', 'sans-serif'],
        'geist-thin': ['Geist_100Thin', 'sans-serif'],
        'geist-extralight': ['Geist_200ExtraLight', 'sans-serif'],
        'geist-light': ['Geist_300Light', 'sans-serif'],
        'geist-medium': ['Geist_500Medium', 'sans-serif'],
        'geist-semibold': ['Geist_600SemiBold', 'sans-serif'],
        'geist-bold': ['Geist_700Bold', 'sans-serif'],
        'geist-extrabold': ['Geist_800ExtraBold', 'sans-serif'],
        'geist-black': ['Geist_900Black', 'sans-serif'],
      },
      colors: {
        light: {
        'background': '#FFFFFF',
        'background-secondary': '#F8FAFC',
        'background-muted': '#F1F5F9',
        'foreground': '#1E293B',
        'foreground-secondary': '#334155',
        'foreground-muted': '#64748B',
        'card': '#FFFFFF',
        'card-foreground': '#1E293B',
        'border': '#E2E8F0',
        'input': '#F1F5F9',
        'ring': '#3B82F6',
        'primary': '#3B82F6',
        'primary-foreground': '#FFFFFF',
        'secondary': '#F1F5F9',
        'secondary-foreground': '#1E293B',
        'success': '#10B981',
        'warning': '#F59E0B',
        'error': '#EF4444',
        'info': '#3B82F6',
        },
        dark: {
        'background': '#171717',
        'background-secondary': '#BABABA',
        'background-muted': '#A3A3A3',
        'foreground': '#FFFFFF',
        'foreground-secondary': '#BABABA',
        'foreground-muted': '#94A3B8',
        'card': '#1E293B',
        'card-foreground': '#F1F5F9',
        'border': '#334155',
        'input': '#334155',
        'ring': '#60A5FA',
        'primary': '#3B82F6',
        'primary-foreground': '#1E293B',
        'secondary': '#334155',
        'secondary-foreground': '#F1F5F9',
        'success': '#34D399',
        'warning': '#FBBF24',
        'error': '#F87171',
        'info': '#60A5FA',
        },
      },
      backgroundImage: {
        'gradient-gray': 'linear-gradient(180deg, #868686 0%, #5B5B5B 100%)',
        'gradient-accent': 'linear-gradient(180deg, #3B82F6 0%, #5898FF 100%)',
      },
    },
  },
  plugins: [],
};